network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - 192.168.100.1/24
      nameservers:
        addresses: [1.1.1.1]
  wifis:
    wlan0:
      optional: true
      dhcp4: true
      access-points:
        "DEATH-STAR":
          auth:
            key-management: "psk"
            password: "SECRET!!!!!!"
